### ISSUE TITLE
Search Button is not working (bug & feature request)

### ISSUE THREAD

**Issue by amitanshusahu** [KiranAminPanjwani/LeatherHoard#57]
## To-Do 📝
- [ ] working search button which match the ui
- [ ] autosuggestion for products , useful links , and redirects
- [ ] caching searched data to show in recent search

### Screenshots

![image](https://user-images.githubusercontent.com/83657737/193425913-e9ebd050-af06-400c-a0a5-d0caf7ccb59f.png)

**Comment by amitanshusahu** [comment]
### @KiranAminPanjwani ,  I would like to work on this 😄 
given it's open for hacktoberfest2022 🌟

**Comment by KiranAminPanjwani** [comment]
Yeah sure, please go ahead! 🤩
